# Generated by Django 4.2.6 on 2023-12-02 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0003_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2023, 12, 2, 10, 20, 33, 24283, tzinfo=datetime.timezone.utc
                ),
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
